version: '3'
services:
  sut: 
    #build: .
    image: 5899797fc3e8
    #image: ppiper/mta-archive-builder
    volumes:
      - ./test/goss:/goss-test
    working_dir: /goss-test

    command:
      - /bin/sh
      - -c
      - |
          mkdir .goss
          curl -fsSL https://goss.rocks/install | GOSS_DST=.goss sh
          .goss/goss --gossfile goss.yaml validate
          # cleanup
          rm -rf .goss .mta
    #command: ".goss/goss --gossfile /goss-tests/goss.yaml validate"
