# CMD: docker-compose --file docker-compose.test.yml up
version: '3'
services:
  goss:
    image: aelsabbahy/goss
    volumes:
      - goss-executable:/goss
    command: goss --version
  sut:
    build: .
    depends_on: 
      - goss
    volumes:
      - goss-executable:/goss
      - ./test/goss:/tests
    working_dir: /tests
    command: /goss/goss --gossfile goss.yaml validate
volumes:
  goss-executable:
